# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=y
CONFIG_USB_CDC_ACM_RINGBUF_SIZE=16384
#CONFIG_ZMK_LOG_LEVEL=4
CONFIG_LOG=y
#CONFIG_DEBUG=y

CONFIG_USB_HID_POLL_INTERVAL_MS=1

##CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
##CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0

#CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
##CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

CONFIG_ZMK_SLEEP=y
#CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

#CONFIG_ZMK_KSCAN_DIRECT_POLLING=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=300

#maybe enable this some day when OS gets better
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=n

CONFIG_ZMK_STUDIO=y

#CONFIG_BT_DEVICE_NAME="Asanoha"
#CONFIG_ZMK_KEYBOARD_NAME="Asanoha"
