CONFIG_ZMK_USB_LOGGING=n
#CONFIG_USB_CDC_ACM_RINGBUF_SIZE=16384
#CONFIG_ZMK_LOG_LEVEL=4
CONFIG_LOG=n
#CONFIG_ZMK_LOG_LEVEL_DBG=n
#CONFIG_DEBUG=n

#CONFIG_BT=y
#CONFIG_ZMK_BLE=y

#CONFIG_ZMK_USB=n

#CONFIG_ZMK_KSCAN_DIRECT_POLLING=y
#CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

#CONFIG_PINCTRL=y
#CONFIG_GPIO=y
#CONFIG_I2C=y

CONFIG_ZMK_SLEEP=y
#CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
